---
- hosts: web
  gather_facts: No
  tasks:
  - name: Enable EPEL repo
    dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      disable_gpg_check: true

  - name: Install nginx and needed network package
    dnf:
      name: ['nginx', 'iproute']

  #Facts needed for template
  - setup:

  - name: Create index.html
    template:
      src: ./templates/index.html.j2
      dest: /usr/share/nginx/html/index.html

  - name: Start nginx
    service: name=nginx state=started enabled=yes
